{
    "CVE_data_meta": {
        "ASSIGNER": "security@ubuntu.com",
        "DATE_PUBLIC": "2019-12-12T17:47:00.000Z",
        "ID": "CVE-2019-15796",
        "STATE": "PUBLIC",
        "TITLE": "python-apt downloads from untrusted sources",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "0.8.3ubuntu7.5"
                                },
                                {
                                    "version_value": "0.9.3.5ubuntu3+esm2"
                                },
                                {
                                    "version_value": "1.1.0~beta1ubuntu0.16.04.7"
                                },
                                {
                                    "version_value": "1.6.5ubuntu0.1"
                                },
                                {
                                    "version_value": "1.9.0ubuntu1.2"
                                },
                                {
                                    "version_value": "1.9.5"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "Canonical"
                }
            ]
        },
        "configuration": [],
        "credits": [
            {
                "lang": "eng",
                "value": "Julian Andres Klode"
            }
        ],
        "descriptions": [
            {
                "lang": "eng",
                "value": "Python-apt doesn't check if hashes are signed in `Version.fetch_binary()` and `Version.fetch_source()` of apt/package.py or in `_fetch_archives()` of apt/cache.py in version 1.9.3ubuntu2 and earlier. This allows downloads from unsigned repositories which shouldn't be allowed and has been fixed in verisions 1.9.5, 1.9.0ubuntu1.2, 1.6.5ubuntu0.1, 1.1.0~beta1ubuntu0.16.04.7, 0.9.3.5ubuntu3+esm2, and 0.8.3ubuntu7.5."
            }
        ],
        "exploit": [],
        "generator": {
            "engine": "Vulnogram 0.0.9"
        },
        "metrics": [
            {
                "cvss-v_3_1": {
                    "attackComplexity": "HIGH",
                    "attackVector": "NETWORK",
                    "availabilityImpact": "NONE",
                    "baseScore": 4.7,
                    "baseSeverity": "MEDIUM",
                    "confidentialityImpact": "LOW",
                    "integrityImpact": "LOW",
                    "privilegesRequired": "NONE",
                    "scope": "CHANGED",
                    "userInteraction": "REQUIRED",
                    "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:L/I:L/A:N",
                    "version": "3.1"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-287 Improper Authentication",
                        "description": "CWE-287 Improper Authentication",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/4247-1/"
            },
            {
                "name": "",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/4247-3/"
            }
        ],
        "solution": [],
        "source": {
            "advisory": "https://usn.ubuntu.com/4247-1/",
            "defect": [
                "https://bugs.launchpad.net/bugs/1858973"
            ],
            "discovery": "UNKNOWN"
        },
        "work_around": []
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}