{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2014-1624",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "Race condition in the xdg.BaseDirectory.get_runtime_dir function in python-xdg 0.25 allows local users to overwrite arbitrary files by pre-creating /tmp/pyxdg-runtime-dir-fallback-victim to point to a victim-owned location, then replacing it with a symlink to an attacker-controlled location once the get_runtime_dir function is called."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "[oss-security] 20140121 Re: Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2014/01/21/4"
            },
            {
                "name": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247",
                "refsource": "MISC",
                "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=736247"
            },
            {
                "name": "pythonxdg-cve20141624-symlink(90618)",
                "refsource": "XF",
                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/90618"
            },
            {
                "name": "65042",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/65042"
            },
            {
                "name": "[oss-security] 20140121 Fwd: [Python-modules-team] Bug#736247: python-xdg: get_runtime_dir(strict=False): insecure use of /tmp",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2014/01/21/3"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}