{
    "CVE_data_meta": {
        "ASSIGNER": "report@snyk.io",
        "ID": "CVE-2019-10742",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "through 0.18.0"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "axios"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "Axios up to and including 0.18.0 allows attackers to cause a denial of service (application crash) by continuing to accepting content after maxContentLength is exceeded."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505",
                "refsource": "MISC",
                "url": "https://app.snyk.io/vuln/SNYK-JS-AXIOS-174505"
            },
            {
                "name": "https://github.com/axios/axios/issues/1098",
                "refsource": "MISC",
                "url": "https://github.com/axios/axios/issues/1098"
            },
            {
                "name": "https://github.com/axios/axios/pull/1485",
                "refsource": "MISC",
                "url": "https://github.com/axios/axios/pull/1485"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}