{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2009-2701",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "Unspecified vulnerability in the Zope Enterprise Objects (ZEO) storage-server functionality in Zope Object Database (ZODB) 3.8 before 3.8.3 and 3.9.x before 3.9.0c2, when certain ZEO database sharing and blob support are enabled, allows remote authenticated users to read or delete arbitrary files via unknown vectors."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "[zope-announce] 20090901 CVE-2009-2701: Releases to fix ZODB ZEO server vulnerability",
                "refsource": "MLIST",
                "url": "https://mail.zope.org/pipermail/zope-announce/2009-September/002221.html"
            },
            {
                "name": "http://pypi.python.org/pypi/ZODB3/3.8.3",
                "refsource": "CONFIRM",
                "url": "http://pypi.python.org/pypi/ZODB3/3.8.3"
            },
            {
                "name": "ADV-2009-2534",
                "refsource": "VUPEN",
                "url": "http://www.vupen.com/english/advisories/2009/2534"
            },
            {
                "name": "http://pypi.python.org/pypi/ZODB3/3.9.0c2",
                "refsource": "CONFIRM",
                "url": "http://pypi.python.org/pypi/ZODB3/3.9.0c2"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}