{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2015-3206",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "[oss-security] 20150521 CVE-2015-3206 python-kerberos: checkPassword() does not verify KDC authenticity",
                "refsource": "MLIST",
                "url": "http://www.openwall.com/lists/oss-security/2015/05/21/3"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1223802"
            },
            {
                "name": "https://pypi.python.org/pypi/kerberos",
                "refsource": "CONFIRM",
                "url": "https://pypi.python.org/pypi/kerberos"
            },
            {
                "name": "74760",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/74760"
            },
            {
                "name": "https://github.com/apple/ccs-pykerberos/issues/31",
                "refsource": "CONFIRM",
                "url": "https://github.com/apple/ccs-pykerberos/issues/31"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}