{
    "CVE_data_meta": {
        "ASSIGNER": "cve@mitre.org",
        "ID": "CVE-2008-7263",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "ftpserver.py in pyftpdlib before 0.5.0 does not delay its response after receiving an invalid login attempt, which makes it easier for remote attackers to obtain access via a brute-force attack."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn348&r=348&format=side&path=/trunk/pyftpdlib/ftpserver.py",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn348&r=348&format=side&path=/trunk/pyftpdlib/ftpserver.py"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/issues/detail?id=73",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=73"
            },
            {
                "name": "http://code.google.com/p/pyftpdlib/source/detail?r=348",
                "refsource": "CONFIRM",
                "url": "http://code.google.com/p/pyftpdlib/source/detail?r=348"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}