{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2016-4989",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "n/a"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "n/a",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461"
            },
            {
                "name": "RHSA-2016:1267",
                "refsource": "REDHAT",
                "url": "https://rhn.redhat.com/errata/RHSA-2016-1267.html"
            },
            {
                "name": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad",
                "refsource": "CONFIRM",
                "url": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad"
            },
            {
                "name": "[oss-security] 20160621 SELinux troubles",
                "refsource": "MLIST",
                "url": "http://seclists.org/oss-sec/2016/q2/574"
            },
            {
                "name": "RHSA-2016:1293",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2016:1293"
            },
            {
                "name": "1036144",
                "refsource": "SECTRACK",
                "url": "http://securitytracker.com/id/1036144"
            },
            {
                "name": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f",
                "refsource": "CONFIRM",
                "url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}